name = "4"
type = "javascript"
account_id = "d1574ff4d207bc23602cc79fc78b7b2a"
workers_dev = true
compatibility_date = "2021-12-26"

[[kv_namespaces]]
binding = "G"
id = "8cc4b2e13c7845e99f2d69a6ec48e906"

# [vars]
# HOOK_PATH = "/"
# TELEGRAM_API_TOKEN = "5017904403:AAFY1cZFRuN1HN3aSn-YDPenR5y8i5t3jaQ"
# TOKEN = "5017904403:AAFY1cZFRuN1HN3aSn-YDPenR5y8i5t3jaQ"
# ALLOWED_CHAT_IDS = "5043676235,-1001570134152,-1001739992180"

[build]
command = ""
[build.upload]
format = "modules"
main = "./index.mjs"
